# permissions for end users to edit cryptodatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cryptodatabase-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crypto-platform-operator
    app.kubernetes.io/part-of: crypto-platform-operator
    app.kubernetes.io/managed-by: kustomize
  name: cryptodatabase-editor-role
rules:
- apiGroups:
  - database.crypto.com
  resources:
  - cryptodatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.crypto.com
  resources:
  - cryptodatabases/status
  verbs:
  - get
