# permissions for end users to view cryptocaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cryptocache-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crypto-platform-operator
    app.kubernetes.io/part-of: crypto-platform-operator
    app.kubernetes.io/managed-by: kustomize
  name: cryptocache-viewer-role
rules:
- apiGroups:
  - database.crypto.com
  resources:
  - cryptocaches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.crypto.com
  resources:
  - cryptocaches/status
  verbs:
  - get
