apiVersion: app.crypto.com/v1alpha1
kind: CryptoTracker
metadata:
  labels:
    app.kubernetes.io/name: cryptotracker
    app.kubernetes.io/instance: cryptotracker-sample
    app.kubernetes.io/part-of: crypto-platform-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: crypto-platform-operator
  name: cryptotracker-sample
spec:
  # TODO(user): Add fields here
