apiVersion: database.crypto.com/v1alpha1
kind: CryptoCache
metadata:
  labels:
    app.kubernetes.io/name: cryptocache
    app.kubernetes.io/instance: cryptocache-sample
    app.kubernetes.io/part-of: crypto-platform-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: crypto-platform-operator
  name: cryptocache-sample
spec:
  # TODO(user): Add fields here
